project_id = "qiwndzsrmtxmgngnupml"

[functions.generate-meal-plan]
verify_jwt = false

[functions.generate-daily-nutrition]
verify_jwt = false

[functions.estimate-macros]
verify_jwt = true

[functions.nutrition-ai]
verify_jwt = true

[functions.calculate-nutrition-score]
verify_jwt = true


[functions.parse-training-plan]
verify_jwt = true

[functions.refresh-meal-plan]
verify_jwt = false

[functions.generate-nutrition-suggestions]
verify_jwt = false

[functions.refresh-expiring-google-tokens]
verify_jwt = false

[functions.sync-all-users-direct]
verify_jwt = false

[functions.sync-all-google-fit-data]
verify_jwt = false

[functions.test-db-connection]
verify_jwt = false

[functions.update-actual-training]
verify_jwt = false

[functions.gamification]
verify_jwt = true

[functions.fetch-google-fit-data]
verify_jwt = false

[functions.sync-historical-google-fit-data]
verify_jwt = false

[functions.generate-meal-plan-simple]
verify_jwt = false

[functions.generate-meal-plan-range]
verify_jwt = false

[functions.refresh-all-google-tokens]
verify_jwt = false
