project_id = "qiwndzsrmtxmgngnupml"

[functions.generate-meal-plan]
verify_jwt = false

[functions.generate-daily-nutrition]
verify_jwt = false

[functions.estimate-macros]
verify_jwt = true

[functions.nutrition-ai]
verify_jwt = true

[functions.calculate-nutrition-score]
verify_jwt = true

[functions.parse-fit-data]
verify_jwt = true

[functions.parse-training-plan]
verify_jwt = true

[functions.refresh-meal-plan]
verify_jwt = false