name = "nutrisync"
compatibility_date = "2024-01-01"
account_id = "5a73505af9ed48e44ce4caeaa0fdf73f"

# Pages configuration
pages_build_output_dir = "dist"

[env.production]
name = "nutrisync"
pages_build_output_dir = "dist"

[env.preview]
name = "nutrisync-preview"
pages_build_output_dir = "dist"