// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Single source of truth: VITE env; allow optional window globals for runtime override in index.html
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const w: any = (typeof window !== 'undefined' ? window : {}) as any;
const SUPABASE_URL = ((import.meta as any).env?.VITE_SUPABASE_URL || w.__SUPABASE_URL__) as string;

// Use ONLY anon key for client SDK (Realtime + REST). Do not fall back to publishable.
const SUPABASE_ANON_KEY = ((import.meta as any).env?.VITE_SUPABASE_ANON_KEY || w.__SUPABASE_ANON_KEY__) as string;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  },
  // Slightly lower event rate to reduce disconnects; rely on anon key above
  realtime: { params: { eventsPerSecond: 2 } }
});

// Expose globally for any legacy callers that expect window.supabase
try {
  if (typeof window !== 'undefined') {
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    (window as any).supabase = supabase;
  }
} catch {}

// Fail-fast with a clear error if env vars are not configured
const missingUrl = !(((import.meta as any).env?.VITE_SUPABASE_URL) || w.__SUPABASE_URL__);
const missingKey = !(((import.meta as any).env?.VITE_SUPABASE_ANON_KEY) || (w.__SUPABASE_ANON_KEY__));
const usingPlaceholders = false;

if (missingUrl || missingKey || usingPlaceholders) {
  const message = [
    'Supabase environment variables are not configured.',
    'Set VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in .env.local',
    'See SUPABASE_MIGRATION_GUIDE.md (Step 3).'
  ].join(' ');
  // eslint-disable-next-line no-console
  console.warn(message, {
    VITE_SUPABASE_URL: ((import.meta as any).env?.VITE_SUPABASE_URL || w.__SUPABASE_URL__) ? 'SET' : 'NOT SET',
    VITE_SUPABASE_ANON_KEY: ((import.meta as any).env?.VITE_SUPABASE_ANON_KEY || w.__SUPABASE_ANON_KEY__) ? 'SET' : 'NOT SET',
  });
}

export const SUPABASE_READY = !(missingUrl || missingKey || usingPlaceholders);

if (SUPABASE_READY) {
  // eslint-disable-next-line no-console
  console.info('[Supabase] Environment detected:', {
    VITE_SUPABASE_URL: (import.meta.env.VITE_SUPABASE_URL || '').replace(/^(https:\/\/)([^.]+)(.*)$/,'$1***$3'),
    VITE_SUPABASE_ANON_KEY: 'SET',
  });
}